apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: kafkamanager/kafka-manager
        name: kafka
        env:
          # Use secret in real usage
         - name: ZK_HOSTS
           value: /var/lib/zoekeeper/data
        ports:
        - containerPort: 9092
          name: kafka
        volumeMounts:
        - name: kafka-persistent-storage
          mountPath: /var/lib/kafka
      volumes:
      - name: kafka-persistent-storage
        persistentVolumeClaim:
          claimName: kafka-pv-claim