#persistent volume for mysql database

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
data:
  custommysql.cnf: |
    [mysql]
    bind-address = 0.0.0.0
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"custommysql.cnf":"[mysql]\nbind-address = 0.0.0.0\n"},"kind":"ConfigMap","metadata":{"annotations":{},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:custommysql.cnf":{}}},"manager":"kubectl-create","operation":"Update"}],"name":"mysql-config","namespace":"default"}}
  creationTimestamp: "2020-11-27T09:30:42Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:custommysql.cnf: {}
    manager: kubectl-create
    operation: Update
  name: mysql-config
  namespace: default
  resourceVersion: "13192"
  selfLink: /api/v1/namespaces/default/configmaps/mysql-config
  uid: b750ba7a-6a77-48f0-94ad-83114395d936

